/**
 * Border snapshot handling + timeline cross-fade math.
 *
 * We do NOT compute borders live. We keep a handful of pre-baked GeoJSON
 * snapshots and blend the opacity of the two nearest ones as the slider moves,
 * which looks like a continuous morph for a fraction of the cost.
 */

import type { FeatureCollection } from "geojson";
import b1224 from "@/data/borders/1224.json";
import b1240 from "@/data/borders/1240.json";
import b1266 from "@/data/borders/1266.json";
import b1313 from "@/data/borders/1313.json";
import b1357 from "@/data/borders/1357.json";
import b1395 from "@/data/borders/1395.json";
import b1430 from "@/data/borders/1430.json";
import b1466 from "@/data/borders/1466.json";
import b1502 from "@/data/borders/1502.json";

export const YEAR_MIN = 1206;
export const YEAR_MAX = 1502;

const GOLDEN = "Алтын Орда · Golden Horde";
const GREAT = "Ұлы Орда · Great Horde";

export type BorderSnapshot = {
  year: number;
  /** Short map label drawn over the territory for this era. */
  label: string;
  data: FeatureCollection;
};

/**
 * Nine era snapshots — growth, peak, and collapse. Generated by
 * scripts/gen-borders.mjs. MUST stay sorted ascending by year.
 */
export const BORDER_SNAPSHOTS: BorderSnapshot[] = [
  { year: 1224, label: "Жошы Ұлысы · Ulus of Jochi", data: b1224 as FeatureCollection },
  { year: 1240, label: GOLDEN, data: b1240 as FeatureCollection },
  { year: 1266, label: GOLDEN, data: b1266 as FeatureCollection },
  { year: 1313, label: GOLDEN, data: b1313 as FeatureCollection },
  { year: 1357, label: GOLDEN, data: b1357 as FeatureCollection },
  { year: 1395, label: GOLDEN, data: b1395 as FeatureCollection },
  { year: 1430, label: GOLDEN, data: b1430 as FeatureCollection },
  { year: 1466, label: GREAT, data: b1466 as FeatureCollection },
  { year: 1502, label: GREAT, data: b1502 as FeatureCollection },
];

/**
 * Rough centroid (average of the outer ring's vertices) of the first polygon
 * in a snapshot, returned as Leaflet [lat, lng]. Good enough for placing a
 * label over the territory; not a true area-weighted centroid.
 */
export function snapshotCentroid(fc: FeatureCollection): [number, number] {
  const feature = fc.features[0];
  const geom = feature?.geometry;
  let ring: number[][] = [];
  if (geom?.type === "Polygon") {
    ring = geom.coordinates[0];
  } else if (geom?.type === "MultiPolygon") {
    ring = geom.coordinates[0][0];
  }
  if (ring.length === 0) return [50, 55];

  // Drop the closing vertex if the ring is explicitly closed.
  const pts =
    ring.length > 1 &&
    ring[0][0] === ring[ring.length - 1][0] &&
    ring[0][1] === ring[ring.length - 1][1]
      ? ring.slice(0, -1)
      : ring;

  let sumLng = 0;
  let sumLat = 0;
  for (const [lng, lat] of pts) {
    sumLng += lng;
    sumLat += lat;
  }
  return [sumLat / pts.length, sumLng / pts.length];
}

/**
 * Returns a cross-fade weight in [0, 1] for each snapshot at `currentYear`.
 * The two snapshots bracketing the year share the weight (linear blend);
 * every other snapshot gets 0. Outside the snapshot range, the nearest
 * endpoint gets the full weight.
 */
export function computeBorderWeights(
  currentYear: number,
  snapshots: BorderSnapshot[] = BORDER_SNAPSHOTS
): number[] {
  const weights = new Array(snapshots.length).fill(0);
  if (snapshots.length === 0) return weights;

  // Clamp below the earliest / above the latest snapshot.
  if (currentYear <= snapshots[0].year) {
    weights[0] = 1;
    return weights;
  }
  const lastIdx = snapshots.length - 1;
  if (currentYear >= snapshots[lastIdx].year) {
    weights[lastIdx] = 1;
    return weights;
  }

  // Find the bracketing pair [i, i+1].
  for (let i = 0; i < lastIdx; i++) {
    const lo = snapshots[i].year;
    const hi = snapshots[i + 1].year;
    if (currentYear >= lo && currentYear <= hi) {
      const t = (currentYear - lo) / (hi - lo);
      weights[i] = 1 - t;
      weights[i + 1] = t;
      break;
    }
  }
  return weights;
}
